name: Generate Snake Animation 🐍

on:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Yozora13
          outputs: |
            ./output/github-contribution-grid-snake.svg
            ./output/github-contribution-grid-snake-dark.svg

      - name: Auto commit & push snake
        uses: EndBug/add-and-commit@v9
        with:
          message: "🐍 Update snake animation"
          add: "output/*.svg"
          default_author: github_actions
          pull: true
